package tt;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/** Represents one user or chatbot message in the conversation. */
public class DialogBox extends HBox {
    private static final String ERROR_AVATAR = "!";
    private static final String USER_AVATAR = "You";
    private static final String BOT_AVATAR = "TT";

    private DialogBox(String text, String avatarText, boolean isUser, boolean isError) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(350);

        Label avatar = new Label(avatarText);
        avatar.setMinSize(42, 42);
        avatar.setAlignment(Pos.CENTER);

        if (isUser) {
            message.getStyleClass().add("user-message");
            avatar.getStyleClass().add("user-avatar");
        } else if (isError) {
            message.getStyleClass().add("error-message");
            avatar.getStyleClass().add("error-avatar");
        } else {
            message.getStyleClass().add("bot-message");
            avatar.getStyleClass().add("bot-avatar");
        }

        setSpacing(10);
        setAlignment(isUser ? Pos.TOP_RIGHT : Pos.TOP_LEFT);
        if (isUser) {
            getChildren().addAll(message, avatar);
        } else {
            getChildren().addAll(avatar, message);
        }
    }

    /** Creates a right-aligned dialog for a command entered by the user. */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, USER_AVATAR, true, false);
    }

    /** Creates a left-aligned dialog for a response generated by the chatbot. */
    public static DialogBox getBotDialog(String text) {
        return new DialogBox(text, BOT_AVATAR, false, false);
    }

    /** Creates a visually highlighted dialog for an invalid command. */
    public static DialogBox getErrorDialog(String text) {
        return new DialogBox(text, ERROR_AVATAR, false, true);
    }
}
