package tt;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents one user or chatbot message in the conversation.
 */
public class DialogBox extends HBox {
    private static final String AVATAR_BOT = "TT";
    private static final String AVATAR_ERROR = "!";
    private static final String AVATAR_USER = "You";

    private DialogBox(String text, String avatarText, boolean isUser, boolean isError) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(350);

        Label avatar = new Label(avatarText);
        avatar.setMinSize(42, 42);
        avatar.setAlignment(Pos.CENTER);

        if (isUser) {
            message.getStyleClass().add("user-message");
            avatar.getStyleClass().add("user-avatar");
        } else if (isError) {
            message.getStyleClass().add("error-message");
            avatar.getStyleClass().add("error-avatar");
        } else {
            message.getStyleClass().add("bot-message");
            avatar.getStyleClass().add("bot-avatar");
        }

        setSpacing(10);
        setAlignment(isUser ? Pos.TOP_RIGHT : Pos.TOP_LEFT);
        if (isUser) {
            getChildren().addAll(message, avatar);
        } else {
            getChildren().addAll(avatar, message);
        }
    }

    /**
     * Creates a right-aligned dialog for a command entered by the user.
     *
     * @param text command entered by the user.
     * @return dialog containing the user's command.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, AVATAR_USER, true, false);
    }

    /**
     * Creates a left-aligned dialog for a response generated by the chatbot.
     *
     * @param text response generated by the chatbot.
     * @return dialog containing the chatbot's response.
     */
    public static DialogBox getBotDialog(String text) {
        return new DialogBox(text, AVATAR_BOT, false, false);
    }

    /**
     * Creates a visually highlighted dialog for an invalid command.
     *
     * @param text error explanation to display.
     * @return dialog containing the highlighted error.
     */
    public static DialogBox getErrorDialog(String text) {
        return new DialogBox(text, AVATAR_ERROR, false, true);
    }
}
