package tt;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/** Represents one user or chatbot message in the conversation. */
public class DialogBox extends HBox {
    private static final String USER_AVATAR = "You";
    private static final String BOT_AVATAR = "TT";

    private DialogBox(String text, String avatarText, boolean isUser) {
        Label message = new Label(text);
        message.setWrapText(true);
        message.setMaxWidth(350);
        message.getStyleClass().add(isUser ? "user-message" : "bot-message");

        Label avatar = new Label(avatarText);
        avatar.setMinSize(42, 42);
        avatar.setAlignment(Pos.CENTER);
        avatar.getStyleClass().add(isUser ? "user-avatar" : "bot-avatar");

        setSpacing(10);
        setAlignment(isUser ? Pos.TOP_RIGHT : Pos.TOP_LEFT);
        if (isUser) {
            getChildren().addAll(message, avatar);
        } else {
            getChildren().addAll(avatar, message);
        }
    }

    /** Creates a right-aligned dialog for a command entered by the user. */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, USER_AVATAR, true);
    }

    /** Creates a left-aligned dialog for a response generated by the chatbot. */
    public static DialogBox getBotDialog(String text) {
        return new DialogBox(text, BOT_AVATAR, false);
    }
}
